version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/${WEB_SERVER}/Dockerfile
    ports:
      - "${WEB_PUBLISHED_PORT:-80}:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
      - redis
      - db
    networks:
      - laravel

  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      # after building docker container, move the variables to the .env file in laravel app
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  db:
    build:
      context: .
      dockerfile: ./docker/${DB_SERVER}/Dockerfile
    environment:
      - ${DB_ENV_VAR}=${DB_PASSWORD}
      - ${DB_DATABASE_VAR}=${DB_DATABASE}
      - ${DB_USER}=${DB_USERNAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - db-store:/var/lib/${DB_SERVER}
    networks:
      - laravel

  redis:
    image: redis:alpine
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - laravel
    restart: unless-stopped
  
  mailpit:
    image: axllent/mailpit
    ports:
      - "${MAILPIT_PUBLISHED_PORT:-8025}:8025"
    networks:
      - laravel

volumes:
  db-store:
    driver: local
  redis:
    driver: local

networks:
    laravel:
        driver: bridge
